apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: pre-prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql-container
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: trainee
            - name: POSTGRES_PASSWORD
              value: trainee
            - name: POSTGRES_DB
              value: app-mydb
          ports:
            - containerPort: 5652
          volumeMounts:
            - name: postgresql-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-storage
          emptyDir: {}
