--
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namspaces: pre-prod
spec:
  selector:
    app: postgresql-pod
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5652

